### ISSUE TITLE
Component breakdown

### ISSUE THREAD

**Issue by bluecondor** [chingu-voyage3/geckos-12#5]
Note: containers are stateful components (class based components). Every other component that does not have container in parentheses is just a presentational component (functional, dumb).

1. App (container)
2. Header (container)
3. Timer - child of Header component
4. WorkerEarnings  - child of Header component
5. SuperMarketEarnings  - child of Header component
6. SuperMarketOwnerEarnings  - child of Header component
7. QuestionMark (Maybe we should drop this one?) - yes just basic icon not a component
9. Language (Could be left out since we are going to do only the English version) - _no, it helps to know how to build a multi language app_
8. FacebookIcon - _components or just icons inside anchor tags in the jsx?_
9. TwitterIcon -  _components or just icons  inside anchor tags in the jsx?_
10. GetEngaged
11. Logo
12. LeftNavigation (container)
13. RadioButton
14. Sections (container? Or could also be just a presentational component?) - _might depend on the section_
15. Section
16. Modal (in section 2)
17. Carousel (container)
18. CarouselArrow
19. CarouselDots
20. CarouselSlideDescription
21. Diseases (container) -section 3
22. Disease
23. ValueShareColumn
24. ValueShareEntity
25. Button
26. BananaWorldMap
27. BananaWorldLocation
28. CallToAction
29. Action
30. Footer

**Comment by bluecondor** [comment]
8. Language (Could be left out since we are going to do only the English version) 

> - no, it helps to know how to build a multi language app.

I agree but my initial thought was actually if we will have time. I say we should try to go as far as possible with the EN version and only if we will have time to go further.

9. and 10. Totally agree, no need for components, just icons in the component that will containt them both icons.

15. Sections (container? Or could also be just a presentational component?)

>  - might depend on the section

I think you missunderstood me on this one. Sections (plural) I was thinking is supposed to be only a layout for all the other section, and at this point it can be just a functional component. Inside of this Sections component we will have all the other sections, using a Section component.

**Comment by Umiii** [comment]
- _I agree but my initial thought was actually if we will have time. I say we should try to go as far as possible with the EN version and only if we will have time to go further._

**Ok agreed**

_and 10. Totally agree, no need for components, just icons in the component that will containt them both icons._

**Ok cool**

_I think you missunderstood me on this one. Sections (plural) I was thinking is supposed to be only a layout for all the other section, and at this point it can be just a functional component. Inside of this Sections component we will have all the other sections, using a Section component._

**Oh i thought you meant 'section' - Singular, ok it sounds good to me.**
